# Describes the format for available Pura services

start_timer:
  name: Start timer
  description: Start a fragrance timer.
  target:
    device:
      - integration: pura
    entity:
      - integration: pura
  fields:
    slot:
      name: Slot
      description: Fragrance slot. Leave blank to automatically select the fragrance with the most scent remaining (based on runtime).
      required: false
      example: 1
      selector:
        select:
          options:
            - "1"
            - "2"
    intensity:
      name: Intensity
      description: Fragrance intensity.
      required: true
      example: 4
      default: 4
      selector:
        number:
          min: 1
          max: 10
    duration:
      name: Duration
      description: Timer duration.
      required: true
      example: "hours: 0\nminutes: 30\nseconds: 0"
      default:
        hours: 0
        minutes: 30
        seconds: 0
      selector:
        duration:
